### ISSUE TITLE
Problems using GPU

### ISSUE THREAD

**Issue by ccruizm** [theislab/ncem#104]
Good day,

I have tested the building of the model using GPU but seem to have some problems. On our HPC with V100 and RTX6000 I get the message below:
```
2022-07-08 17:43:48.418309: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/ncem/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:22<00:00, 22.25s/it]
100%|██████████| 1/1 [00:22<00:00, 22.25s/it]2022-07-08 17:45:09.445032: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-08 17:45:09.864682: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21322 MB memory:  -> device: 0, name: Quadro RTX 6000, pci bus id: 0000:5e:00.0, compute capability: 7.5
2022-07-08 20:15:32.071303: W tensorflow/core/framework/op_kernel.cc:1733] UNKNOWN: KeyError: 829
Traceback (most recent call last):

  File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/ncem/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/ncem/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/ncem/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1132, in finalize_py_func
    generator_state.iterator_completed(iterator_id)

  File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/ncem/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 853, in iterator_completed
    del self._iterators[self._normalize_id(iterator_id)]

KeyError: 829
```
For this I created a fresh conda environment and only pip installed ncem. The process is still running on CPU but it has alredy taken over four days and still has not finished the training.

I have also tried on another HPC with an A100 GPU. However, there the error is recognizing my GPU
```
2022-07-11 10:23:36.877594: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
/home/cruiz2/miniconda3/envs/ncem/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:18<00:00, 18.96s/it]
100%|██████████| 1/1 [00:18<00:00, 18.96s/it]2022-07-11 10:24:57.496311: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-07-11 10:24:57.496383: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-07-11 10:24:57.505115: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
```
Added `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/cruiz2/miniconda3/envs/ncem/lib/libcudnn.so.8` on my bashrc file but still get the same error. 

Do you have any recomendations on how to set the package to recognize the GPU properly, please? 

Thanks in advance

**Comment by AnnaChristina** [comment]
Hi @ccruizm, your error seems to be related to a wrong CUDA set-up and not directly related to ncem. 

Could you check which CUDA you are using?

**Comment by AnnaChristina** [comment]
Closing the issue due to inactivity. Feel free to open again in case of further questions.
